### ISSUE TITLE
报错了，是失效了吗大佬？

### ISSUE THREAD

**Issue by duceman495** [Illustar0/ZZUPortalAuther#1]
Traceback (most recent call last):
  File "/usr/1/ZZUPortalAuther-main/ZZUPortalAuther.py", line 113, in <module>
    loadConfig(client, baseURL, User_Agent)
  File "/usr/1/ZZUPortalAuther-main/ZZUPortalAuther.py", line 95, in loadConfig
    'wlan_user_ip': base64.b64encode(getIPByInterface(interface).encode()).decode(),
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by Illustar0** [comment]
~~至少今天中午我这边还是好的 (~~
仍然可用
大概率是 psutil 没有获取到对应接口的 IP，返回了 None ，因为是自用所以没有做异常处理。
你看看 config.toml 里的 interface 都对应上了么

**Comment by Illustar0** [comment]
不是哥们，不看 Github 的吗

**Comment by Illustar0** [comment]
长时间不回复
